service: app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  function1:
    handler: index.handler
    events:
      - httpApi:
          path: /hello
          method: get
    layers:
      - arn:aws:lambda:us-east-1:144842881551:layer:PrivateModules:1
