service: mememaker
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
plugins:
  - serverless-offline
functions:
  mememaker:
    handler: index.mememaker
    events:
      - httpApi:
          method: get
          path: /mememaker
